################################### Default Configuration ############################

baseurl = "https://nuvibit.com/"
theme = "vex-hugo"
summarylength = "20"
googleAnalytics = "G-65QED8XYJ9"
disableLanguages = []
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

########################### Default Parameters ##########################

[params]
logo_banner = "images/logo/logo-nuvibit-banner.png"
logo_footer = "images/logo/logo-nuvibit-badge.png"
contact_form_url = "https://forms.nuvibit.com/nuvibit/form/Contactus/formperma/TUZO-GqMg11XIInReyJqMICqAS7hWGm6YdW3oVM32hE"
copyright = "Copyright © 2021 - 2023 Nuvibit AG"
author = "Nuvibit AG"

#################################### Privacy ##########################################

[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false

[privacy.instagram]
disable = true
simple = false

[privacy.twitter]
disable = true
enableDNT = false
simple = false

[privacy.vimeo]
disable = true
enableDNT = false
simple = false

[privacy.youtube]
disable = true
privacyEnhanced = false

################################### English Language #####################################

[Languages.en]
languageName = "english"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
title = "Nuvibit | Revolutionize Your AWS Cloud Infrastructure"

[Languages.en.params]
description = "Simplify cloud management and maximize performance, compliance and scalability with an AWS Landing Zone & Foundation from Nuvibit."

###################################### English Navigation ######################################

[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
identifier = "solutions"
name = "Solutions"
url = "/solutions/"
weight = 2

[[Languages.en.menu.main]]
identifier = "terraform-collection"
name = "Nuvibit Terraform Collection (NTC)"
url = "/solutions/terraform-collection/"
parent = "solutions"
weight = 3

[[Languages.en.menu.main]]
identifier = "semper"
name = "SEMPER"
url = "/solutions/semper/"
parent = "solutions"
weight = 4

[[Languages.en.menu.main]]
identifier = "foundation-blueprint"
name = "Foundation Blueprint"
url = "/solutions/foundation-blueprint/"
parent = "solutions"
weight = 5

[[Languages.en.menu.main]]
identifier = "tools"
name = "Tools"
url = "/tools/"
weight = 6

[[Languages.en.menu.main]]
identifier = "vpc-subnet-calculator"
name = "AWS VPC Subnet Calculator"
url = "/vpc-subnet-calculator/"
parent = "tools"
weight = 7

[[Languages.en.menu.main]]
name = "Blog"
url = "/blog/"
weight = 8

[[Languages.en.menu.main]]
name = "Team"
url = "/team/"
weight = 9

[[Languages.en.menu.main]]
name = "Contact"
url = "/contact/"
weight = 10

###################################### English Footer ######################################

[[Languages.en.menu.footer]]
identifier = "language"
name = "Language"
weight = 1

[[Languages.en.menu.footer]]
identifier = "company"
name = "Company"
weight = 2

[[Languages.en.menu.footer]]
parent = "company"
name = "FAQ"
url = "/faq/"
weight = 3

[[Languages.en.menu.footer]]
parent = "company"
name = "Team"
url = "/team/"
weight = 4

[[Languages.en.menu.footer]]
parent = "company"
name = "Contact"
url = "/contact/"
weight = 5

# [[Languages.en.menu.footer]]
# parent = "company"
# name = "Customers"
# url = "/customers/"
# weight = 6

[[Languages.en.menu.footer]]
parent = "company"
name = "Cookie Policy"
url = "/privacy-policy/#71-cookies"
weight = 7

[[Languages.en.menu.footer]]
parent = "company"
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 8

[[Languages.en.menu.footer]]
identifier = "social"
name = "Social Media"
weight = 9

[[Languages.en.menu.footer]]
parent = "social"
name = "Github"
url = "https://github.com/nuvibit"
weight = 10

[[Languages.en.menu.footer]]
parent = "social"
name = "Linkedin"
url = "https://linkedin.com/company/nuvibit"
weight = 11

[[Languages.en.menu.footer]]
parent = "social"
name = "Twitter"
url = "https://twitter.com/nuvibit"
weight = 12

[[Languages.en.menu.footer]]
parent = "social"
name = "Youtube"
url = "https://www.youtube.com/channel/UCmQCd8jMiZviVlWOqqbpYBw/playlists"
weight = 13

################################### German Language #####################################

[Languages.de]
languageName = "german"
languageCode = "de-de"
contentDir = "content/deutsch"
weight = 2
title = "Nuvibit | Revolutionieren Sie Ihre AWS Cloud-Infrastruktur"

[Languages.de.params]
description = "Vereinfachtes Cloud-Management und maximale Performance, Compliance und Skalierbarkeit mit einer AWS Landing Zone & Foundation von Nuvibit."

###################################### German Navigation ######################################

[[Languages.de.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.de.menu.main]]
identifier = "solutions"
name = "Solutions"
url = "/solutions/"
weight = 2

[[Languages.de.menu.main]]
identifier = "terraform-collection"
name = "Nuvibit Terraform Collection (NTC)"
url = "/solutions/terraform-collection/"
parent = "solutions"
weight = 3

[[Languages.de.menu.main]]
identifier = "semper"
name = "SEMPER"
url = "/solutions/semper/"
parent = "solutions"
weight = 4

[[Languages.de.menu.main]]
identifier = "foundation-blueprint"
name = "Foundation Blueprint"
url = "/solutions/foundation-blueprint/"
parent = "solutions"
weight = 5

[[Languages.de.menu.main]]
identifier = "tools"
name = "Tools"
url = "/tools/"
weight = 6

[[Languages.de.menu.main]]
identifier = "vpc-subnet-calculator"
name = "AWS VPC Subnetzrechner"
url = "/vpc-subnet-calculator/"
parent = "tools"
weight = 7

[[Languages.de.menu.main]]
name = "Blog"
url = "/blog/"
weight = 8

[[Languages.de.menu.main]]
name = "Team"
url = "/team/"
weight = 9

[[Languages.de.menu.main]]
name = "Kontakt"
url = "/contact/"
weight = 10

###################################### German Footer ######################################

[[Languages.de.menu.footer]]
identifier = "language"
name = "Sprache"
weight = 1

[[Languages.de.menu.footer]]
identifier = "company"
name = "Unternehmen"
weight = 2

[[Languages.de.menu.footer]]
parent = "company"
name = "FAQ"
url = "/faq/"
weight = 3

[[Languages.de.menu.footer]]
parent = "company"
name = "Team"
url = "/team/"
weight = 4

[[Languages.de.menu.footer]]
parent = "company"
name = "Kontakt"
url = "/contact/"
weight = 5

# [[Languages.de.menu.footer]]
# parent = "company"
# name = "Kunden"
# url = "/customers/"
# weight = 6

[[Languages.de.menu.footer]]
parent = "company"
name = "Cookie Richtlinien"
url = "/privacy-policy/#71-cookies"
weight = 7

[[Languages.de.menu.footer]]
parent = "company"
name = "Datenschutzerklärung"
url = "/privacy-policy/"
weight = 8

[[Languages.de.menu.footer]]
identifier = "social"
name = "Soziale Medien"
weight = 9

[[Languages.de.menu.footer]]
parent = "social"
name = "Github"
url = "https://github.com/nuvibit"
weight = 10

[[Languages.de.menu.footer]]
parent = "social"
name = "Linkedin"
url = "https://linkedin.com/company/nuvibit"
weight = 11

[[Languages.de.menu.footer]]
parent = "social"
name = "Twitter"
url = "https://twitter.com/nuvibit"
weight = 12

[[Languages.de.menu.footer]]
parent = "social"
name = "Youtube"
url = "https://www.youtube.com/channel/UCmQCd8jMiZviVlWOqqbpYBw/playlists"
weight = 13

###################################### DEVELOPMENT ######################################

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Access-Control-Allow-Origin = '*'
    Strict-Transport-Security = 'max-age=63072000; includeSubdomains; preload'
    Content-Security-Policy = "default-src 'self' forms.nuvibit.com; img-src 'self' data: https://www.google-analytics.com; script-src 'self' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com 'sha256-XZjOLS67JdKgeeMB3dbqndAgpwfz7EvsT1rX5iv3p1s='; style-src 'self' fonts.googleapis.com; object-src 'none'; font-src 'self' fonts.gstatic.com; connect-src 'self' https://*.google-analytics.com;"
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'


###################################### DEPLOYMENT ######################################

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = ["images/*"]

[[deployment.targets]]
  name = "aws"
  URL = "s3://www.nuvibit.com?region=eu-central-1&prefix=public/"
  cloudFrontDistributionID = "E12OG0KGSMQIU3"