################################### Default Configuration ############################

baseurl = "https://nuvibit.com/"
title = "Nuvibit"
theme = "vex-hugo"
# post excert
summarylength = "20"

# google analytics
googleAnalytics = "G-65QED8XYJ9"
# disable language
disableLanguages = []
# check all links for correct absolute language url before enabling language

# unsafe html
[markup.goldmark.renderer]
unsafe = true

# robots
enableRobotsTXT = true

#################################### Privacy ##########################################

[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = true
simple = false

[privacy.twitter]
disable = true
enableDNT = false
simple = false

[privacy.vimeo]
disable = true
enableDNT = false
simple = false

[privacy.youtube]
disable = true
privacyEnhanced = false

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Open%20Sans:400|Nunito:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "plugins/cookieconsent/cookieconsent.min.css"
[[params.plugins.css]]
link = "plugins/snow/snow.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/cookieconsent/cookieconsent.min.js"
[[params.plugins.js]]
link = "plugins/snow/snow.min.js"
[[params.plugins.js]]
link = "plugins/ipaddr/ipaddr.js"

########################### Default Parameters ##########################

[params]
logo_banner = "images/logo/logo-nuvibit-banner.png"
logo_banner_width = "200px"
logo_footer = "images/logo/logo-nuvibit-badge.png"
logo_footer_width = "175px"
# Meta data
description = "We help you build an enterprise ready, compliant and scalable foundation for the public cloud."
author = "Nuvibit AG"
contact_form_url = "https://forms.zohopublic.eu/nuvibit/form/Contactus/formperma/TUZO-GqMg11XIInReyJqMICqAS7hWGm6YdW3oVM32hE"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader/snake.gif"

################################### English Language #####################################

[Languages.en]
languageName = "english"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
copyright = "Copyright © 2023 - Nuvibit AG"

###################################### English Navigation ######################################

# homepage section menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
identifier = "services"
name = "Services"
url = "services"
weight = 2

[[Languages.en.menu.main]]
identifier = "assistance"
name = "Cloud Assistance"
url = "services/assistance"
parent = "services"
weight = 3

[[Languages.en.menu.main]]
identifier = "management"
name = "Cloud Management at Scale"
url = "services/management"
parent = "services"
weight = 4

[[Languages.en.menu.main]]
identifier = "security"
name = "Cloud Security and Compliance"
url = "services/security"
parent = "services"
weight = 5

[[Languages.en.menu.main]]
identifier = "connectivity"
name = "Cloud Connectivity"
url = "services/connectivity"
parent = "services"
weight = 6

[[Languages.en.menu.main]]
identifier = "solutions"
name = "Solutions"
url = "solutions"
weight = 7

[[Languages.en.menu.main]]
identifier = "foundation-blueprint"
name = "Foundation Blueprint"
url = "solutions/foundation-blueprint"
parent = "solutions"
weight = 8

[[Languages.en.menu.main]]
identifier = "semper"
name = "SEMPER"
url = "solutions/semper"
parent = "solutions"
weight = 9

[[Languages.en.menu.main]]
identifier = "tools"
name = "Tools"
url = "tools"
weight = 10

[[Languages.en.menu.main]]
identifier = "subnet-calculator"
name = "VPC Subnet Calculator"
url = "subnet-calculator"
parent = "tools"
weight = 11

[[Languages.en.menu.main]]
identifier = "terraform-collection"
name = "Terraform Collection"
url = "terraform-collection"
parent = "tools"
weight = 12

[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 13

[[Languages.en.menu.main]]
name = "Team"
url = "team"
weight = 14

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 15

###################################### English Footer ######################################

[[Languages.en.menu.footer]]
identifier = "language"
name = "Language"
weight = 1

[[Languages.en.menu.footer]]
identifier = "company"
name = "Company"
weight = 2

[[Languages.en.menu.footer]]
parent = "company"
name = "FAQ"
url = "/faq"
weight = 3

[[Languages.en.menu.footer]]
parent = "company"
name = "Team"
url = "/team"
weight = 4

[[Languages.en.menu.footer]]
parent = "company"
name = "Contact"
url = "/contact"
weight = 5

# [[Languages.en.menu.footer]]
# parent = "company"
# name = "Customers"
# url = "/customers"
# weight = 6

[[Languages.en.menu.footer]]
parent = "company"
name = "Cookie Policy"
url = "/privacy-policy/#51-cookies"
weight = 7

[[Languages.en.menu.footer]]
parent = "company"
name = "Privacy Policy"
url = "/privacy-policy"
weight = 8

[[Languages.en.menu.footer]]
identifier = "social"
name = "Social Media"
weight = 9

[[Languages.en.menu.footer]]
parent = "social"
name = "Github"
url = "https://github.com/nuvibit"
weight = 10

[[Languages.en.menu.footer]]
parent = "social"
name = "Linkedin"
url = "https://linkedin.com/company/nuvibit"
weight = 11

[[Languages.en.menu.footer]]
parent = "social"
name = "Twitter"
url = "https://twitter.com/nuvibit"
weight = 12

[[Languages.en.menu.footer]]
parent = "social"
name = "Youtube"
url = "https://www.youtube.com/channel/UCmQCd8jMiZviVlWOqqbpYBw/playlists"
weight = 13

################################### German Language #####################################

[Languages.de]
languageName = "german"
languageCode = "de-de"
contentDir = "content/deutsch"
weight = 2
# copyright
copyright = "Urheberrechte © 2023 - Nuvibit AG"

###################################### German Navigation ######################################

# homepage section menu
[[Languages.de.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.de.menu.main]]
identifier = "services"
name = "Services"
url = "services"
weight = 2

[[Languages.de.menu.main]]
identifier = "assistance"
name = "Cloud Assistance"
url = "services/assistance"
parent = "services"
weight = 3

[[Languages.de.menu.main]]
identifier = "management"
name = "Cloud Management at Scale"
url = "services/management"
parent = "services"
weight = 4

[[Languages.de.menu.main]]
identifier = "security"
name = "Cloud Security and Compliance"
url = "services/security"
parent = "services"
weight = 5

[[Languages.de.menu.main]]
identifier = "connectivity"
name = "Cloud Connectivity"
url = "services/connectivity"
parent = "services"
weight = 6

[[Languages.de.menu.main]]
identifier = "solutions"
name = "Lösungen"
url = "solutions"
weight = 7

[[Languages.de.menu.main]]
identifier = "foundation-blueprint"
name = "Foundation Blueprint"
url = "solutions/foundation-blueprint"
parent = "solutions"
weight = 8

[[Languages.de.menu.main]]
identifier = "semper"
name = "SEMPER"
url = "solutions/semper"
parent = "solutions"
weight = 9

[[Languages.de.menu.main]]
identifier = "tools"
name = "Tools"
url = "tools"
weight = 10

[[Languages.de.menu.main]]
identifier = "subnet-calculator"
name = "VPC Subnetz Rechner"
url = "subnet-calculator"
parent = "tools"
weight = 11

[[Languages.de.menu.main]]
identifier = "terraform-collection"
name = "Terraform Sammlung"
url = "terraform-collection"
parent = "tools"
weight = 12

[[Languages.de.menu.main]]
name = "Blog"
url = "blog"
weight = 13

[[Languages.de.menu.main]]
name = "Team"
url = "team"
weight = 14

[[Languages.de.menu.main]]
name = "Kontakt"
url = "contact"
weight = 15

###################################### German Footer ######################################

[[Languages.de.menu.footer]]
identifier = "language"
name = "Sprache"
weight = 1

[[Languages.de.menu.footer]]
identifier = "company"
name = "Unternehmen"
weight = 2

[[Languages.de.menu.footer]]
parent = "company"
name = "FAQ"
url = "/faq"
weight = 3

[[Languages.de.menu.footer]]
parent = "company"
name = "Team"
url = "/team"
weight = 4

[[Languages.de.menu.footer]]
parent = "company"
name = "Kontakt"
url = "/contact"
weight = 5

# [[Languages.de.menu.footer]]
# parent = "company"
# name = "Kunden"
# url = "/customers"
# weight = 6

[[Languages.de.menu.footer]]
parent = "company"
name = "Cookie Richtlinien"
url = "/privacy-policy/#51-cookies"
weight = 7

[[Languages.de.menu.footer]]
parent = "company"
name = "Datenschutzerklärung"
url = "/privacy-policy"
weight = 8

[[Languages.de.menu.footer]]
identifier = "social"
name = "Soziale Medien"
weight = 9

[[Languages.de.menu.footer]]
parent = "social"
name = "Github"
url = "https://github.com/nuvibit"
weight = 10

[[Languages.de.menu.footer]]
parent = "social"
name = "Linkedin"
url = "https://linkedin.com/company/nuvibit"
weight = 11

[[Languages.de.menu.footer]]
parent = "social"
name = "Twitter"
url = "https://twitter.com/nuvibit"
weight = 12

[[Languages.de.menu.footer]]
parent = "social"
name = "Youtube"
url = "https://www.youtube.com/channel/UCmQCd8jMiZviVlWOqqbpYBw/playlists"
weight = 13
