name: HUGO BUILD

on:
  push:
    branches:
      - main

jobs:
  terraform-workspace:
    uses: nuvibit/github-workflows/.github/workflows/hugo-build.yml@v1
    secrets:
      GH_SA_TOKEN_RO: ${{ secrets.GH_SA_TOKEN_RO }}
